% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={practica 2},
  pdfauthor={Elena Canton y Manuel E. Escobar},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{practica 2}
\author{Elena Canton y Manuel E. Escobar}
\date{7/5/2021}

\begin{document}
\maketitle

\hypertarget{descripciuxf3n-del-dataset.-por-quuxe9-es-importante-y-quuxe9-preguntaproblema-pretende-responder}{%
\subsection{1. Descripción del dataset. ¿Por qué es importante y qué
pregunta/problema pretende
responder?}\label{descripciuxf3n-del-dataset.-por-quuxe9-es-importante-y-quuxe9-preguntaproblema-pretende-responder}}

El conjunto de datos objeto de análisis se ha obtenido a partir de este
enlace en Kaggle. El dataset está formado por 12 variables (columnas) y
1599 registrs (filas).

Enlace:
\url{https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009?select=winequality-red.csv}

Estas son las variables del conjunto de datos: 1 - fixed acidity 2 -
volatile acidity 3 - citric acid 4 - residual sugar 5 - chlorides 6 -
free sulfur dioxide 7 - total sulfur dioxide 8 - density 9 - pH 10 -
sulphates 11 - alcohol Output variable (based on sensory data): 12 -
quality (score between 0 and 10)

La principal característica de estos datos es la calidad. Con este
estudio se pretende esclarecer cuáles de las características afectan a
la puntuación de dicha calidad, con valores de entre 0 y 10.

Además, en la descripción del dataset publicado, ya se nos informa de
que no hay valores perdidos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Carga de los datos}
\CommentTok{\#setwd("C:/")}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}winequality{-}red.csv\textquotesingle{}}\NormalTok{, }\AttributeTok{sep=}\StringTok{\textquotesingle{},\textquotesingle{}}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   fixed.acidity volatile.acidity citric.acid residual.sugar chlorides
## 1           7.4             0.70        0.00            1.9     0.076
## 2           7.8             0.88        0.00            2.6     0.098
## 3           7.8             0.76        0.04            2.3     0.092
## 4          11.2             0.28        0.56            1.9     0.075
## 5           7.4             0.70        0.00            1.9     0.076
## 6           7.4             0.66        0.00            1.8     0.075
##   free.sulfur.dioxide total.sulfur.dioxide density   pH sulphates alcohol
## 1                  11                   34  0.9978 3.51      0.56     9.4
## 2                  25                   67  0.9968 3.20      0.68     9.8
## 3                  15                   54  0.9970 3.26      0.65     9.8
## 4                  17                   60  0.9980 3.16      0.58     9.8
## 5                  11                   34  0.9978 3.51      0.56     9.4
## 6                  13                   40  0.9978 3.51      0.56     9.4
##   quality
## 1       5
## 2       5
## 3       5
## 4       6
## 5       5
## 6       5
\end{verbatim}

Mostramos el resumen del conjunto de datos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1599 obs. of  12 variables:
##  $ fixed.acidity       : num  7.4 7.8 7.8 11.2 7.4 7.4 7.9 7.3 7.8 7.5 ...
##  $ volatile.acidity    : num  0.7 0.88 0.76 0.28 0.7 0.66 0.6 0.65 0.58 0.5 ...
##  $ citric.acid         : num  0 0 0.04 0.56 0 0 0.06 0 0.02 0.36 ...
##  $ residual.sugar      : num  1.9 2.6 2.3 1.9 1.9 1.8 1.6 1.2 2 6.1 ...
##  $ chlorides           : num  0.076 0.098 0.092 0.075 0.076 0.075 0.069 0.065 0.073 0.071 ...
##  $ free.sulfur.dioxide : num  11 25 15 17 11 13 15 15 9 17 ...
##  $ total.sulfur.dioxide: num  34 67 54 60 34 40 59 21 18 102 ...
##  $ density             : num  0.998 0.997 0.997 0.998 0.998 ...
##  $ pH                  : num  3.51 3.2 3.26 3.16 3.51 3.51 3.3 3.39 3.36 3.35 ...
##  $ sulphates           : num  0.56 0.68 0.65 0.58 0.56 0.56 0.46 0.47 0.57 0.8 ...
##  $ alcohol             : num  9.4 9.8 9.8 9.8 9.4 9.4 9.4 10 9.5 10.5 ...
##  $ quality             : int  5 5 5 6 5 5 5 7 7 5 ...
\end{verbatim}

La variable str nos permite ver que hay 12 variables y 1599
observaciones. La variable respuesta es ``quality'', la calidad del
vino. El conjunto cuenta con 11 variables predictoras de clase numérica,
y 1 de tipo integer, quality.

Además, vamos a realizar un análisis exploratorio de los datos. La
función summary nos proporciona un resumen estadístico sobre las
variables (mínimo, máximo, media, mediana, primer y tercer cuartil).
Además, si hay valores faltantes también nos informará.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Revisamos el dataset.}
\FunctionTok{summary}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  fixed.acidity   volatile.acidity  citric.acid    residual.sugar  
##  Min.   : 4.60   Min.   :0.1200   Min.   :0.000   Min.   : 0.900  
##  1st Qu.: 7.10   1st Qu.:0.3900   1st Qu.:0.090   1st Qu.: 1.900  
##  Median : 7.90   Median :0.5200   Median :0.260   Median : 2.200  
##  Mean   : 8.32   Mean   :0.5278   Mean   :0.271   Mean   : 2.539  
##  3rd Qu.: 9.20   3rd Qu.:0.6400   3rd Qu.:0.420   3rd Qu.: 2.600  
##  Max.   :15.90   Max.   :1.5800   Max.   :1.000   Max.   :15.500  
##    chlorides       free.sulfur.dioxide total.sulfur.dioxide    density      
##  Min.   :0.01200   Min.   : 1.00       Min.   :  6.00       Min.   :0.9901  
##  1st Qu.:0.07000   1st Qu.: 7.00       1st Qu.: 22.00       1st Qu.:0.9956  
##  Median :0.07900   Median :14.00       Median : 38.00       Median :0.9968  
##  Mean   :0.08747   Mean   :15.87       Mean   : 46.47       Mean   :0.9967  
##  3rd Qu.:0.09000   3rd Qu.:21.00       3rd Qu.: 62.00       3rd Qu.:0.9978  
##  Max.   :0.61100   Max.   :72.00       Max.   :289.00       Max.   :1.0037  
##        pH          sulphates         alcohol         quality     
##  Min.   :2.740   Min.   :0.3300   Min.   : 8.40   Min.   :3.000  
##  1st Qu.:3.210   1st Qu.:0.5500   1st Qu.: 9.50   1st Qu.:5.000  
##  Median :3.310   Median :0.6200   Median :10.20   Median :6.000  
##  Mean   :3.311   Mean   :0.6581   Mean   :10.42   Mean   :5.636  
##  3rd Qu.:3.400   3rd Qu.:0.7300   3rd Qu.:11.10   3rd Qu.:6.000  
##  Max.   :4.010   Max.   :2.0000   Max.   :14.90   Max.   :8.000
\end{verbatim}

Enumeramos el número de variables del data set.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "fixed.acidity"        "volatile.acidity"     "citric.acid"         
##  [4] "residual.sugar"       "chlorides"            "free.sulfur.dioxide" 
##  [7] "total.sulfur.dioxide" "density"              "pH"                  
## [10] "sulphates"            "alcohol"              "quality"
\end{verbatim}

Visualizamos el tipo de datos de cada variable del conjunto de datos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Tipo de dato asignado a cada campo}
\FunctionTok{sapply}\NormalTok{(data, }\ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{class}\NormalTok{(x))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fixed.acidity     volatile.acidity          citric.acid 
##            "numeric"            "numeric"            "numeric" 
##       residual.sugar            chlorides  free.sulfur.dioxide 
##            "numeric"            "numeric"            "numeric" 
## total.sulfur.dioxide              density                   pH 
##            "numeric"            "numeric"            "numeric" 
##            sulphates              alcohol              quality 
##            "numeric"            "numeric"            "integer"
\end{verbatim}

Obbservamos que son todas numericas.

\hypertarget{integraciuxf3n-y-selecciuxf3n-de-los-datos-de-interuxe9s-a-analizar.}{%
\subsection{2. Integración y selección de los datos de interés a
analizar.}\label{integraciuxf3n-y-selecciuxf3n-de-los-datos-de-interuxe9s-a-analizar.}}

En el caso de los datos utilizados para esta practica solamente hay un
dataset.La integración o fusión de los datos consiste en la combinación
de datos procedentes de múltiples fuentes, con el fin de crear una
estructura de datos coherente y única que contenga mayor cantidad de
información. De lo anterior, el aparatado de integración no aplica al
conjunto de datos seleccionados.

selección de variables: Ideas a valorar solo analizar las muestras cuya
calidad sea superior al 7

En esta fase también es habitual realizar una exploración de los datos
(screening, en inglés), con el objetivo de analizar globalmente sus
características e identificar fuertes correlaciones entre atributos, de
modo que se pueda prescindir de aquella información más redundante.

Idea a valorar: podríamos analizar las variables. análisis de
componentes principales (ACP), apartado análisis de componentes
principales (ACP),

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#Análisis de componentes principales (ACP),}
\NormalTok{data.pca }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(data[,}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{11}\NormalTok{)], }\AttributeTok{center =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{scale =} \ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(data.pca)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Importance of components:
##                           PC1    PC2    PC3    PC4     PC5     PC6     PC7
## Standard deviation     1.7604 1.3878 1.2452 1.1015 0.97943 0.81216 0.76406
## Proportion of Variance 0.2817 0.1751 0.1410 0.1103 0.08721 0.05996 0.05307
## Cumulative Proportion  0.2817 0.4568 0.5978 0.7081 0.79528 0.85525 0.90832
##                            PC8     PC9    PC10    PC11
## Standard deviation     0.65035 0.58706 0.42583 0.24405
## Proportion of Variance 0.03845 0.03133 0.01648 0.00541
## Cumulative Proportion  0.94677 0.97810 0.99459 1.00000
\end{verbatim}

El resultado son 11 componentes principales (PC1-PC11), cada una de las
cuales explica un porcentaje de varianza del dataset original. Así, la
primera componente principal explica un poco menos de las 2/3 de la
varianza total y las 5 primeras componentes describen en torno al 80 \%
de la varianza. Dado que las ocho primeras componentes ya explican en
torno al 95 \% de la varianza,

\hypertarget{limpieza-de-los-datos.}{%
\subsection{3. Limpieza de los datos.}\label{limpieza-de-los-datos.}}

\hypertarget{los-datos-contienen-ceros-o-elementos-vacuxedos-cuxf3mo-gestionaruxedas-cada-uno-de-estos-casos}{%
\subsubsection{3.1. ¿Los datos contienen ceros o elementos vacíos? ¿Cómo
gestionarías cada uno de estos
casos?}\label{los-datos-contienen-ceros-o-elementos-vacuxedos-cuxf3mo-gestionaruxedas-cada-uno-de-estos-casos}}

Tras aplicar la función summary, hemos podido observar que no hay ningún
valor perdido en ninguna de las variables del dataset, aunque a veces
los datasets, en lugar de contener NA o simplemente no tener ningún
valor asignado (campo vacío), tienen 0. Sin embargo en este caso,
podemos observar que solo la variable Citric acid tiene algún valor 0.

Igualmente vamos a proceder a realizar algunos test para la gestión de
estos valores.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Números de valores desconocidos por campo}
\FunctionTok{sapply}\NormalTok{(data, }\ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(x)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fixed.acidity     volatile.acidity          citric.acid 
##                    0                    0                    0 
##       residual.sugar            chlorides  free.sulfur.dioxide 
##                    0                    0                    0 
## total.sulfur.dioxide              density                   pH 
##                    0                    0                    0 
##            sulphates              alcohol              quality 
##                    0                    0                    0
\end{verbatim}

Se observa que no existen valores NA en el dataset, lo cual coincide con
la descripción localizada en la url donde se aloja el conjunto de datos
estudiado.

A continuación analizamos las variables con valores igual a 0 dentro del
conjunto de datos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#vemos que porcentaje por columnas tienen los valores 0}
\FunctionTok{colSums}\NormalTok{(data}\SpecialCharTok{==}\DecValTok{0}\NormalTok{)}\SpecialCharTok{/}\FunctionTok{nrow}\NormalTok{(data)}\SpecialCharTok{*}\DecValTok{100}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fixed.acidity     volatile.acidity          citric.acid 
##             0.000000             0.000000             8.255159 
##       residual.sugar            chlorides  free.sulfur.dioxide 
##             0.000000             0.000000             0.000000 
## total.sulfur.dioxide              density                   pH 
##             0.000000             0.000000             0.000000 
##            sulphates              alcohol              quality 
##             0.000000             0.000000             0.000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Números de valores 0 por campo}
\FunctionTok{colSums}\NormalTok{(data}\SpecialCharTok{==}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fixed.acidity     volatile.acidity          citric.acid 
##                    0                    0                  132 
##       residual.sugar            chlorides  free.sulfur.dioxide 
##                    0                    0                    0 
## total.sulfur.dioxide              density                   pH 
##                    0                    0                    0 
##            sulphates              alcohol              quality 
##                    0                    0                    0
\end{verbatim}

Respuesta: Se observa que existen valores 0, en la variable
``citric.acid'' hay 132 observaciones igual a 0.

Analizamos la posible existencia de valores no informados.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Números de valores enpty por campo}
\FunctionTok{sapply}\NormalTok{(data, }\ControlFlowTok{function}\NormalTok{(x) }\FunctionTok{sum}\NormalTok{(data}\SpecialCharTok{==}\StringTok{""}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fixed.acidity     volatile.acidity          citric.acid 
##                    0                    0                    0 
##       residual.sugar            chlorides  free.sulfur.dioxide 
##                    0                    0                    0 
## total.sulfur.dioxide              density                   pH 
##                    0                    0                    0 
##            sulphates              alcohol              quality 
##                    0                    0                    0
\end{verbatim}

Respuesta: Se observa que no existen campos no informados en el dataset.

\hypertarget{identificaciuxf3n-y-tratamiento-de-valores-extremos.}{%
\subsubsection{3.2. Identificación y tratamiento de valores
extremos.}\label{identificaciuxf3n-y-tratamiento-de-valores-extremos.}}

Respuesta: A continuación vamos a explorar más detalladamente las
variables para analizar la existencia de valores extremos.

Analizamos la distribución de los valores y realizamos un box-plot por
variable.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{ncol}\NormalTok{(data))\{}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.numeric}\NormalTok{(data[,i]))\{}
  \FunctionTok{boxplot}\NormalTok{(data[,i], }\AttributeTok{main =} \FunctionTok{colnames}\NormalTok{(data)[i],}\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#76D7C4"}\NormalTok{)))}
\NormalTok{  \}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-1.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-2.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-3.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-4.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-5.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-6.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-7.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-8.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-9.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-10.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-11.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-11-12.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{ncol}\NormalTok{(data))\{}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.numeric}\NormalTok{(data[,i]))\{}
  \FunctionTok{hist}\NormalTok{(data[,i], }\AttributeTok{main =} \FunctionTok{colnames}\NormalTok{(data)[i],}\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#ff6961"}\NormalTok{)))}
\NormalTok{  \}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-1.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-2.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-3.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-4.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-5.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-6.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-7.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-8.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-9.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-10.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-11.pdf}
\includegraphics{Practica2_files/figure-latex/unnamed-chunk-12-12.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attach}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Observamos la distribuccion de los valores de la variable :citric.acid}
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(citric.acid, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(citric.acid, }\AttributeTok{main=}\StringTok{"citric acid"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-14-1.pdf}

En la Variable ``citric.acid'' se entiende que las observaciones pueden
ser valores reales y que estan correctamente informados. De lo anterior
no aplicaremos transformaciones para estos datos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(fixed.acidity, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(fixed.acidity, }\AttributeTok{main=}\StringTok{"fixed acidity"}\NormalTok{,}\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-15-1.pdf} En
la Variable ``fixed.acidity'' se entiende que las observaciones pueden
ser valores reales y que estan correctamente informados. De lo anterior
no aplicaremos transformaciones para estos datos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(volatile.acidity, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(volatile.acidity, }\AttributeTok{main=}\StringTok{"volatile acidity"}\NormalTok{,}\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-16-1.pdf}

En la Variable ``volatile.acidity'' se entiende que las observaciones
pueden ser valores reales y que estan correctamente informados. De lo
anterior no aplicaremos transformaciones para estos datos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(residual.sugar, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(residual.sugar, }\AttributeTok{main=}\StringTok{"residual sugar"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-17-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#existen mas de 150 valores extremos en esta variable. Vamos a visualizarlos:}
\FunctionTok{boxplot.stats}\NormalTok{(residual.sugar)}\SpecialCharTok{$}\NormalTok{out}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1]  6.10  6.10  3.80  3.90  4.40 10.70  5.50  5.90  5.90  3.80  5.10  4.65
##  [13]  4.65  5.50  5.50  5.50  5.50  7.30  7.20  3.80  5.60  4.00  4.00  4.00
##  [25]  4.00  7.00  4.00  4.00  6.40  5.60  5.60 11.00 11.00  4.50  4.80  5.80
##  [37]  5.80  3.80  4.40  6.20  4.20  7.90  7.90  3.70  4.50  6.70  6.60  3.70
##  [49]  5.20 15.50  4.10  8.30  6.55  6.55  4.60  6.10  4.30  5.80  5.15  6.30
##  [61]  4.20  4.20  4.60  4.20  4.60  4.30  4.30  7.90  4.60  5.10  5.60  5.60
##  [73]  6.00  8.60  7.50  4.40  4.25  6.00  3.90  4.20  4.00  4.00  4.00  6.60
##  [85]  6.00  6.00  3.80  9.00  4.60  8.80  8.80  5.00  3.80  4.10  5.90  4.10
##  [97]  6.20  8.90  4.00  3.90  4.00  8.10  8.10  6.40  6.40  8.30  8.30  4.70
## [109]  5.50  5.50  4.30  5.50  3.70  6.20  5.60  7.80  4.60  5.80  4.10 12.90
## [121]  4.30 13.40  4.80  6.30  4.50  4.50  4.30  4.30  3.90  3.80  5.40  3.80
## [133]  6.10  3.90  5.10  5.10  3.90 15.40 15.40  4.80  5.20  5.20  3.75 13.80
## [145] 13.80  5.70  4.30  4.10  4.10  4.40  3.70  6.70 13.90  5.10  7.80
\end{verbatim}

Se decide que los valores por encima de 10 van a ser considerados
outliers.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#asignamos el valor NA a los casos que van a ser considerados outliers}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{residual.sugar[data}\SpecialCharTok{$}\NormalTok{residual.sugar}\SpecialCharTok{\textgreater{}}\DecValTok{10}\NormalTok{ ] }\OtherTok{\textless{}{-}} \ConstantTok{NA}
\FunctionTok{boxplot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{residual.sugar)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-19-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{idx }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{residual.sugar))}
\FunctionTok{length}\NormalTok{(idx) }\CommentTok{\#número de valores perdidos}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 11
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Imputamos el valor de la mediana a los valores NA.}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(idx))\{}
\NormalTok{index }\OtherTok{\textless{}{-}}\NormalTok{ idx[i]}
\NormalTok{data[index,]}\SpecialCharTok{$}\NormalTok{residual.sugar }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{( data}\SpecialCharTok{$}\NormalTok{residual.sugar, }\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{ ) }\CommentTok{\#imputación}
\NormalTok{\}}
\CommentTok{\#mostramos los valores imputados a los NA}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{residual.sugar[idx] }\CommentTok{\#mostramos el resultado}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2 2.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{residual.sugar, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{residual.sugar, }\AttributeTok{main=}\StringTok{"residual sugar"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-22-1.pdf}
Volvemos a mostrar la distribucion de los datos de la variable
residual.sugar , para comprobar que no exiten valores por encima de 10.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(chlorides, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(chlorides, }\AttributeTok{main=}\StringTok{"chlorides"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-23-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#existen más de 100 valores extremos en esta variable}
\FunctionTok{boxplot.stats}\NormalTok{(chlorides)}\SpecialCharTok{$}\NormalTok{out}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1] 0.176 0.170 0.368 0.341 0.172 0.332 0.464 0.401 0.467 0.122 0.178 0.146
##  [13] 0.236 0.610 0.360 0.270 0.039 0.337 0.263 0.611 0.358 0.343 0.186 0.213
##  [25] 0.214 0.121 0.122 0.122 0.128 0.120 0.159 0.124 0.122 0.122 0.174 0.121
##  [37] 0.127 0.413 0.152 0.152 0.125 0.122 0.200 0.171 0.226 0.226 0.250 0.148
##  [49] 0.122 0.124 0.124 0.143 0.222 0.039 0.157 0.422 0.034 0.387 0.415 0.157
##  [61] 0.157 0.243 0.241 0.190 0.132 0.126 0.038 0.165 0.145 0.147 0.012 0.012
##  [73] 0.039 0.194 0.132 0.161 0.120 0.120 0.123 0.123 0.414 0.216 0.171 0.178
##  [85] 0.369 0.166 0.166 0.136 0.132 0.132 0.123 0.123 0.123 0.403 0.137 0.414
##  [97] 0.166 0.168 0.415 0.153 0.415 0.267 0.123 0.214 0.214 0.169 0.205 0.205
## [109] 0.039 0.235 0.230 0.038
\end{verbatim}

De manera análoga a la variable anterior, se decide considerar outliers
a los valores superiores a 0,3. A estas observaciones se les asignará el
valor de la mediana.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#asignamos el valor NA a los casos que van a ser considerados outliers}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{chlorides[data}\SpecialCharTok{$}\NormalTok{chlorides}\SpecialCharTok{\textgreater{}}\FloatTok{0.3}\NormalTok{ ] }\OtherTok{\textless{}{-}} \ConstantTok{NA}
  
\NormalTok{idx }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{chlorides))}
\FunctionTok{length}\NormalTok{(idx) }\CommentTok{\#número de valores perdidos  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 22
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Imputamos el valor de la mediana a los valores NA.}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(idx))\{}
\NormalTok{index }\OtherTok{\textless{}{-}}\NormalTok{ idx[i]}
\NormalTok{data[index,]}\SpecialCharTok{$}\NormalTok{chlorides }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{( data}\SpecialCharTok{$}\NormalTok{chlorides, }\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{ ) }\CommentTok{\#imputación}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{chlorides, }\AttributeTok{main=}\StringTok{"chlorides"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))  }
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-26-1.pdf}

Volvemos a mostrar la distribución de los datos de la variable chlorides
, para comprobar que no exiten valores por encima de 10.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(free.sulfur.dioxide, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(free.sulfur.dioxide, }\AttributeTok{main=}\StringTok{"sulfur dioxide"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-27-1.pdf}

Vamos a considerar outliers los valores por encima de 60. A estas
observaciones se les asignará el valor de la mediana.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#asignamos el valor NA a los casos que van a ser considerados outliers}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{free.sulfur.dioxide[data}\SpecialCharTok{$}\NormalTok{free.sulfur.dioxide}\SpecialCharTok{\textgreater{}}\DecValTok{60}\NormalTok{ ] }\OtherTok{\textless{}{-}} \ConstantTok{NA}
\NormalTok{idx }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{free.sulfur.dioxide))}
\FunctionTok{length}\NormalTok{(idx) }\CommentTok{\#número de valores perdidos    }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Imputamos el valor de la mediana a los valores NA.}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(idx))\{}
\NormalTok{index }\OtherTok{\textless{}{-}}\NormalTok{ idx[i]}
\NormalTok{data[index,]}\SpecialCharTok{$}\NormalTok{free.sulfur.dioxide }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{( data}\SpecialCharTok{$}\NormalTok{free.sulfur.dioxide, }\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{ ) }\CommentTok{\#imputación}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{free.sulfur.dioxide, }\AttributeTok{main=}\StringTok{"sulfur dioxide"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{))) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-29-1.pdf}

Revisamos que ya no exsistan valores por encima de 60 en esta variable.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(total.sulfur.dioxide, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(total.sulfur.dioxide, }\AttributeTok{main=}\StringTok{"total sulfur dioxide"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-30-1.pdf}

Vamos a considerar outliers los valores por encima de 170. A estas
observaciones se les asignará el valor de la mediana.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#asignamos el valor NA a los casos que van a ser considerados outliers}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{total.sulfur.dioxide[data}\SpecialCharTok{$}\NormalTok{total.sulfur.dioxide}\SpecialCharTok{\textgreater{}}\DecValTok{170}\NormalTok{ ] }\OtherTok{\textless{}{-}} \ConstantTok{NA}
\NormalTok{idx }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{total.sulfur.dioxide))}
\FunctionTok{length}\NormalTok{(idx) }\CommentTok{\#número de valores perdidos    }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Imputamos el valor de la mediana a los valores NA.}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(idx))\{}
\NormalTok{index }\OtherTok{\textless{}{-}}\NormalTok{ idx[i]}
\NormalTok{data[index,]}\SpecialCharTok{$}\NormalTok{total.sulfur.dioxide }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{( data}\SpecialCharTok{$}\NormalTok{total.sulfur.dioxide, }\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{ ) }\CommentTok{\#imputación}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{total.sulfur.dioxide, }\AttributeTok{main=}\StringTok{"total sulfur dioxide"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{))) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-32-1.pdf}
Comprobamos que ya no exiten valores por encima de 170.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(density, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(density, }\AttributeTok{main=}\StringTok{"density"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-33-1.pdf}

En la Variable ``density'' se entiende que las observaciones pueden ser
valores reales y que estan correctamente informadas. De lo anterior no
aplicaremos transformaciones para estos datos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(pH, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(pH, }\AttributeTok{main=}\StringTok{"pH"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-34-1.pdf}

En la Variable ``ph'' se entiende que las observaciones pueden ser
valores reales y que están correctamente informados. De lo anterior no
aplicaremos transformaciones para estos datos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(sulphates, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(sulphates, }\AttributeTok{main=}\StringTok{"sulphates"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-35-1.pdf}

Vamos a considerar outliers los valores por encima de 1,5. A estas
observaciones se les asignará el valor de la mediana.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#asignamos el valor NA a los casos que van a ser considerados outliers}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{sulphates[data}\SpecialCharTok{$}\NormalTok{sulphates}\SpecialCharTok{\textgreater{}}\FloatTok{1.5}\NormalTok{ ] }\OtherTok{\textless{}{-}} \ConstantTok{NA}
 
\NormalTok{idx }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{sulphates))}
\FunctionTok{length}\NormalTok{(idx) }\CommentTok{\#número de valores perdidos    }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Imputamos el valor de la mediana a los valores NA.}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(idx))\{}
\NormalTok{index }\OtherTok{\textless{}{-}}\NormalTok{ idx[i]}
\NormalTok{data[index,]}\SpecialCharTok{$}\NormalTok{sulphates }\OtherTok{\textless{}{-}} \FunctionTok{median}\NormalTok{( data}\SpecialCharTok{$}\NormalTok{sulphates, }\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{ ) }\CommentTok{\#imputación}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{sulphates, }\AttributeTok{main=}\StringTok{"sulphates"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-37-1.pdf}
Comprobamos que ya no exisnte valores por encima de 1,5

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(alcohol, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(alcohol, }\AttributeTok{main=}\StringTok{"alcohol"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-38-1.pdf}

En la Variable ``alcohol'' se entiende que las observaciones pueden ser
valores reales y que están correctamente informadas. De lo anterior no
aplicaremos transformaciones para estos datos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))    }\CommentTok{\# set the plotting area into a 1*2 array}
\FunctionTok{hist}\NormalTok{(quality, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#AA4371"}\NormalTok{)))}
\FunctionTok{boxplot}\NormalTok{(quality, }\AttributeTok{main=}\StringTok{"quality"}\NormalTok{, }\AttributeTok{col=}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"\#0066FF"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-39-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#\#podemos considerarla categoricas}
\end{Highlighting}
\end{Shaded}

\hypertarget{conclusiones-de-los-criterios-adoptados}{%
\subsubsection{Conclusiones de los criterios
adoptados:}\label{conclusiones-de-los-criterios-adoptados}}

residual.sugar: se decide que los valores por encima de 10 van a ser
considerados outliers. chlorides: se decide considerar outliers a los
valores superiores a 0,3 free.sulfur.dioxide: se decide considerar
outliers los valores por encima de 60. total.sulfur.dioxide: se
considerar outliers los valores por encima de 170. sulphates: se decide
considerar outliers los valores por encima de 1,5.

A todos esos casos se ha decidido imputar el valor de la mediana,
exluidos los casos considerados outliers.\\
En el resto de variables. no se han realizado modificaciones de los
datos.

\hypertarget{anuxe1lisis-de-los-datos.}{%
\subsection{4. Análisis de los datos.}\label{anuxe1lisis-de-los-datos.}}

\hypertarget{selecciuxf3n-de-los-grupos-de-datos-que-se-quieren-analizarcomparar-planificaciuxf3n-de-los-anuxe1lisis-a-aplicar.}{%
\subsubsection{4.1. Selección de los grupos de datos que se quieren
analizar/comparar (planificación de los análisis a
aplicar).}\label{selecciuxf3n-de-los-grupos-de-datos-que-se-quieren-analizarcomparar-planificaciuxf3n-de-los-anuxe1lisis-a-aplicar.}}

Análisis de los casos según el nivel de alcohol.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{vinos.calidadAlta }\OtherTok{\textless{}{-}}\NormalTok{ data[data}\SpecialCharTok{$}\NormalTok{quality }\SpecialCharTok{\textgreater{}=} \DecValTok{7}\NormalTok{,]}
\CommentTok{\#Se obtienen 217 observaciones}
\FunctionTok{NROW}\NormalTok{(vinos.calidadAlta)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 217
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#En términos porcentuales supone un 13,57\%}
\FunctionTok{NROW}\NormalTok{(vinos.calidadAlta)}\SpecialCharTok{/}\FunctionTok{NROW}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1357098
\end{verbatim}

Existen 217 muestras cuyos valores de la variable quality es igual o
superior a 7, lo que supone un 13,57\% sobre el total del dataset.

\hypertarget{comprobaciuxf3n-de-la-normalidad-y-homogeneidad-de-la-varianza.}{%
\subsubsection{4.2. Comprobación de la normalidad y homogeneidad de la
varianza.}\label{comprobaciuxf3n-de-la-normalidad-y-homogeneidad-de-la-varianza.}}

Indicar que por el teorema del límite central, podemos asumir
normalidad, puesto que tenemos una muestra de tamaño grande n=1600
observaciones y se desea realizar un test sobre la media.

Analizamos la normalidad la variables con el ad.test de la libreria
nortest.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#install.packages("nortest")}
\FunctionTok{library}\NormalTok{(nortest)}
\NormalTok{alpha }\OtherTok{=} \FloatTok{0.05}
\NormalTok{col.names }\OtherTok{=} \FunctionTok{colnames}\NormalTok{(data)}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{ncol}\NormalTok{(data)) \{}
\ControlFlowTok{if}\NormalTok{ (i }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\FunctionTok{cat}\NormalTok{(}\StringTok{"Variables que no siguen una distribución normal:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.integer}\NormalTok{(data[,i]) }\SpecialCharTok{|} \FunctionTok{is.numeric}\NormalTok{(data[,i])) \{}
\NormalTok{p\_val }\OtherTok{=} \FunctionTok{ad.test}\NormalTok{(data[,i])}\SpecialCharTok{$}\NormalTok{p.value}
\ControlFlowTok{if}\NormalTok{ (p\_val }\SpecialCharTok{\textless{}}\NormalTok{ alpha) \{}
\FunctionTok{cat}\NormalTok{(col.names[i])}
\CommentTok{\# Format output}
\ControlFlowTok{if}\NormalTok{ (i }\SpecialCharTok{\textless{}} \FunctionTok{ncol}\NormalTok{(data) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (i }\SpecialCharTok{\%\%} \DecValTok{3} \SpecialCharTok{==} \DecValTok{0}\NormalTok{) }\FunctionTok{cat}\NormalTok{(}\StringTok{""}\NormalTok{)}
\NormalTok{\}}
\NormalTok{\}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Variables que no siguen una distribución normal:
## fixed.acidity
## volatile.acidity
## citric.acid
## residual.sugar
## chlorides
## free.sulfur.dioxide
## total.sulfur.dioxide
## density
## pH
## sulphates
## alcoholquality
\end{verbatim}

Analizamos la normalidad con el `density plot' y el `qqplot'

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(fixed.acidity),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(fixed.acidity)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-42-1.pdf}
fixed.acidity: parece seguir una distribucion normal observando el
grafico : q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(volatile.acidity),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(volatile.acidity)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-43-1.pdf}

volatile.acidity: parece seguir una distribución normal observando el
grafico : q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(citric.acid),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(citric.acid)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-44-1.pdf}

citric.acid: su extremo izquierdo se desvía de la normal observando el
grafico : q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(residual.sugar),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(residual.sugar)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-45-1.pdf}
residual.sugar: los valores centrales se desvían de la normal observando
el grafico : q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(chlorides),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(chlorides)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-46-1.pdf}
chlorides: los valores centrales se desvían de la normal observando el
grafico : q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(free.sulfur.dioxide),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(free.sulfur.dioxide)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-47-1.pdf}
free.sulfur.dioxide: parece seguir una distribución normal observando el
grafico : q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(total.sulfur.dioxide),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(total.sulfur.dioxide)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-48-1.pdf}
total.sulfur.dioxide: parece seguir una distribución normal observando
el grafico : q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(density),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(density)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-49-1.pdf}
density(density , parece seguir una distribución normal observando el
grafico : q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(pH),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(pH)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-50-1.pdf}
density(pH): parece seguir una distribución normal observando el grafico
: q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(sulphates),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(sulphates)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-51-1.pdf}
sulphates: parece seguir una distribución normal observando el grafico :
q-q

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{density}\NormalTok{(alcohol),}\AttributeTok{main=}\StringTok{"Density"}\NormalTok{)}
\FunctionTok{qqnorm}\NormalTok{(alcohol)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-52-1.pdf}

Seguidamente, pasamos a estudiar la homogeneidad de varianzas mediante
la aplicación de un test de Fligner-Killeen. En este caso, estudiaremos
esta homogeneidad. En el siguiente test, la hipótesis nula consiste en
que ambas varianzas son iguales.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fligner.test}\NormalTok{(quality }\SpecialCharTok{\textasciitilde{}}\NormalTok{ residual.sugar, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Fligner-Killeen test of homogeneity of variances
## 
## data:  quality by residual.sugar
## Fligner-Killeen:med chi-squared = 75.977, df = 82, p-value = 0.6664
\end{verbatim}

Puesto que obtenemos un p-valor superior a 0,05, aceptamos la hipótesis
de que las varianzas de ambas muestras son homogéneas.

\hypertarget{aplicaciuxf3n-de-pruebas-estaduxedsticas-para-comparar-los-grupos-de-datos.-en-funciuxf3n-de-los-datos-y-el-objetivo-del-estudio-aplicar-pruebas-de-contraste-de-hipuxf3tesis-correlaciones-regresiones-etc.-aplicar-al-menos-tres-muxe9todos-de-anuxe1lisis-diferentes.}{%
\subsubsection{4.3. Aplicación de pruebas estadísticas para comparar los
grupos de datos. En función de los datos y el objetivo del estudio,
aplicar pruebas de contraste de hipótesis, correlaciones, regresiones,
etc. Aplicar al menos tres métodos de análisis
diferentes.}\label{aplicaciuxf3n-de-pruebas-estaduxedsticas-para-comparar-los-grupos-de-datos.-en-funciuxf3n-de-los-datos-y-el-objetivo-del-estudio-aplicar-pruebas-de-contraste-de-hipuxf3tesis-correlaciones-regresiones-etc.-aplicar-al-menos-tres-muxe9todos-de-anuxe1lisis-diferentes.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(alcohol)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8.40    9.50   10.20   10.42   11.10   14.90
\end{verbatim}

Contraste de hipótesis:

Se aplica la prueba estadistica de contraste de hipótesis sobre dos
muestras para determinar si el nivel de calidad el vino es diferente
dependiendo de la categoría calculada en función del alcohol. Se
considera nivel bajo de alcohol las muestras con un valor por debajo de
la media (10.42) y nivel alto cuando la muestra tiene un valor superior
o igual a 10.42.

Para ello, tendremos dos categorias: - Vinos con nivel bajo de alcohol -
Vinos con nivel alto de alcohol

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_AlcoholBajo }\OtherTok{\textless{}{-}}\NormalTok{ data[data}\SpecialCharTok{$}\NormalTok{alcohol }\SpecialCharTok{\textless{}} \FloatTok{10.42}\NormalTok{,]}\SpecialCharTok{$}\NormalTok{quality}
\NormalTok{data\_AlcoholAlto }\OtherTok{\textless{}{-}}\NormalTok{ data[data}\SpecialCharTok{$}\NormalTok{alcohol }\SpecialCharTok{\textgreater{}=} \FloatTok{10.42}\NormalTok{,]}\SpecialCharTok{$}\NormalTok{quality}
\end{Highlighting}
\end{Shaded}

Nos preguntamos si la calidad del los vinos puede ser diferente en
función de la categoría creada en función del grado de alcohol de la
muestras. (anteriormente descrita)

En este escenario la hipótesis nula y la alternativa.

H0 : μAlcBajo = μAlcAlto H1 : μAlcBajo =! μAlcAlto

Es un test de dos muestras sobre la media con varianzas desconocidas.
Por el teorema del límite central, podemos asumir normalidad.
Comprobamos igualdad de varianzas:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var.test}\NormalTok{( data\_AlcoholBajo, data\_AlcoholAlto )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  data_AlcoholBajo and data_AlcoholAlto
## F = 0.59219, num df = 915, denom df = 682, p-value = 1.624e-13
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.5142841 0.6809068
## sample estimates:
## ratio of variances 
##          0.5921906
\end{verbatim}

El resultado del test es un valor p\textless0.05. Por tanto, asumimos
diferencias de varianzas. En consecuencia, el test se corresponde con un
test de dos muestras independientes sobre la media con varianzas
desconocidas diferentes. El test es bilateral.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{( data\_AlcoholBajo, data\_AlcoholAlto,}
\AttributeTok{var.equal=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{alternative=}\StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  data_AlcoholBajo and data_AlcoholAlto
## t = -17.688, df = 1237.4, p-value < 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.7569536 -0.6057987
## sample estimates:
## mean of x mean of y 
##  5.344978  6.026354
\end{verbatim}

Conclusión: Nos encontramos con un p-value por debajo de 0.05 por lo que
podemos indicar que podemos aceptar la hipótesis alternativa. Podemos
indicar que la calidad de los vinos es diferente entre los considerados
como nivel bajo de alcohol y los vinos con un nivel alto de alcohol con
un nivel de confianza del 95\%.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#install.packages("ggplot2")}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(}\StringTok{"ggplot2"}\NormalTok{)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{AlcoholCat }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{alcohol }\SpecialCharTok{\textless{}} \FloatTok{10.42}\NormalTok{ , }\StringTok{"Bajo"}\NormalTok{, }\StringTok{"Alto"}\NormalTok{)}
 \CommentTok{\#diagramas de caja:  distribucion de la variable ‘Weight‘ según la variable ‘portero‘}
  \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{AlcoholCat,}\AttributeTok{y=}\NormalTok{quality)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-59-1.pdf}

Representación gráfica del nivel de calidad frente a la categorías
realizadas en función de las variables de alcohol consideradas.

Análisis de la correlación.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corr\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\AttributeTok{nc =} \DecValTok{2}\NormalTok{, }\AttributeTok{nr =} \DecValTok{0}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(corr\_matrix) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"estimate"}\NormalTok{, }\StringTok{"p{-}value"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calcular el coeficiente de correlación para cada variable cuantitativa}
\CommentTok{\# con respecto al campo "quality"}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{ncol}\NormalTok{(data) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)) \{}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.integer}\NormalTok{(data[,i]) }\SpecialCharTok{|} \FunctionTok{is.numeric}\NormalTok{(data[,i])) \{}
\NormalTok{spearman\_test }\OtherTok{=} \FunctionTok{cor.test}\NormalTok{(data[,i],data}\SpecialCharTok{$}\NormalTok{quality,}\AttributeTok{method =} \StringTok{"spearman"}\NormalTok{)}
\NormalTok{corr\_coef }\OtherTok{=}\NormalTok{ spearman\_test}\SpecialCharTok{$}\NormalTok{estimate}
\NormalTok{p\_val }\OtherTok{=}\NormalTok{ spearman\_test}\SpecialCharTok{$}\NormalTok{p.value}
\CommentTok{\# Add row to matrix}
\NormalTok{pair }\OtherTok{=} \FunctionTok{matrix}\NormalTok{(}\AttributeTok{ncol =} \DecValTok{2}\NormalTok{, }\AttributeTok{nrow =} \DecValTok{1}\NormalTok{)}
\NormalTok{pair[}\DecValTok{1}\NormalTok{][}\DecValTok{1}\NormalTok{] }\OtherTok{=}\NormalTok{ corr\_coef}
\NormalTok{pair[}\DecValTok{2}\NormalTok{][}\DecValTok{1}\NormalTok{] }\OtherTok{=}\NormalTok{ p\_val}
\NormalTok{corr\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(corr\_matrix, pair)}
\FunctionTok{rownames}\NormalTok{(corr\_matrix)[}\FunctionTok{nrow}\NormalTok{(corr\_matrix)] }\OtherTok{\textless{}{-}} \FunctionTok{colnames}\NormalTok{(data)[i]}
\NormalTok{\}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties

## Warning in cor.test.default(data[, i], data$quality, method = "spearman"):
## Cannot compute exact p-value with ties
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corr\_matrix}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                         estimate      p-value
## fixed.acidity         0.11408367 4.801220e-06
## volatile.acidity     -0.38064651 2.734944e-56
## citric.acid           0.21348091 6.158952e-18
## residual.sugar        0.03270283 1.912021e-01
## chlorides            -0.18332346 1.494955e-13
## free.sulfur.dioxide  -0.05485346 2.827937e-02
## total.sulfur.dioxide -0.20048430 5.826244e-16
## density              -0.17707407 9.918139e-13
## pH                   -0.04367193 8.084594e-02
## sulphates             0.38395957 2.537306e-57
## alcohol               0.47853169 2.726838e-92
## quality               1.00000000 0.000000e+00
\end{verbatim}

Así, identificamos cuáles son las variables más correlacionadas con la
calidad del vino en función de su proximidad con los valores -1 y +1.
Teniendo esto en cuenta, queda patente cómo la variable más relevante en
la calidad del vino es el alcohol . Nota. Para cada coeficiente de
correlación se muestra también su p-valor asociado, puesto que éste
puede dar información acerca del peso estadístico de la correlación
obtenida.

Correlacion con la variable Quality:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{corr.res}\OtherTok{\textless{}{-}}\FunctionTok{cor}\NormalTok{(data[,}\SpecialCharTok{{-}}\DecValTok{13}\NormalTok{], }\AttributeTok{method=}\StringTok{"spearman"}\NormalTok{)}
\NormalTok{corr.res}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                      fixed.acidity volatile.acidity  citric.acid residual.sugar
## fixed.acidity           1.00000000      -0.27828222  0.661708417     0.22061984
## volatile.acidity       -0.27828222       1.00000000 -0.610259467     0.03838806
## citric.acid             0.66170842      -0.61025947  1.000000000     0.17281554
## residual.sugar          0.22061984       0.03838806  0.172815538     1.00000000
## chlorides               0.24948756       0.16292441  0.085052679     0.23681569
## free.sulfur.dioxide    -0.17026090       0.01908994 -0.074407514     0.06093500
## total.sulfur.dioxide   -0.08851961       0.09732612  0.005880251     0.13128825
## density                 0.62307076       0.02501412  0.352285261     0.41263833
## pH                     -0.70667359       0.23357152 -0.548026276    -0.08406679
## sulphates               0.21263218      -0.32845414  0.329490517     0.04180563
## alcohol                -0.06657566      -0.22493168  0.096455544     0.12950596
## quality                 0.11408367      -0.38064651  0.213480914     0.03270283
##                         chlorides free.sulfur.dioxide total.sulfur.dioxide
## fixed.acidity         0.249487559        -0.170260896         -0.088519608
## volatile.acidity      0.162924412         0.019089943          0.097326120
## citric.acid           0.085052679        -0.074407514          0.005880251
## residual.sugar        0.236815693         0.060935002          0.131288245
## chlorides             1.000000000        -0.005331721          0.128941252
## free.sulfur.dioxide  -0.005331721         1.000000000          0.783791037
## total.sulfur.dioxide  0.128941252         0.783791037          1.000000000
## density               0.414069187        -0.045902592          0.133054752
## pH                   -0.204374649         0.114175693         -0.006302514
## sulphates            -0.022873613         0.044009451         -0.008090304
## alcohol              -0.261929083        -0.080067784         -0.261431180
## quality              -0.183323461        -0.054853464         -0.200484301
##                          density           pH    sulphates     alcohol
## fixed.acidity         0.62307076 -0.706673595  0.212632177 -0.06657566
## volatile.acidity      0.02501412  0.233571519 -0.328454141 -0.22493168
## citric.acid           0.35228526 -0.548026276  0.329490517  0.09645554
## residual.sugar        0.41263833 -0.084066795  0.041805632  0.12950596
## chlorides             0.41406919 -0.204374649 -0.022873613 -0.26192908
## free.sulfur.dioxide  -0.04590259  0.114175693  0.044009451 -0.08006778
## total.sulfur.dioxide  0.13305475 -0.006302514 -0.008090304 -0.26143118
## density               1.00000000 -0.312055078  0.159942063 -0.46244458
## pH                   -0.31205508  1.000000000 -0.067479602  0.17993243
## sulphates             0.15994206 -0.067479602  1.000000000  0.21641153
## alcohol              -0.46244458  0.179932427  0.216411535  1.00000000
## quality              -0.17707407 -0.043671935  0.383959571  0.47853169
##                          quality
## fixed.acidity         0.11408367
## volatile.acidity     -0.38064651
## citric.acid           0.21348091
## residual.sugar        0.03270283
## chlorides            -0.18332346
## free.sulfur.dioxide  -0.05485346
## total.sulfur.dioxide -0.20048430
## density              -0.17707407
## pH                   -0.04367193
## sulphates             0.38395957
## alcohol               0.47853169
## quality               1.00000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#install.packages("corrplot")}
\CommentTok{\#library(corrplot)}
\NormalTok{corrplot}\SpecialCharTok{::}\FunctionTok{corrplot.mixed}\NormalTok{(corr.res, }\AttributeTok{upper=}\StringTok{"ellipse"}\NormalTok{,}\AttributeTok{number.cex=}\NormalTok{.}\DecValTok{6}\NormalTok{,}\AttributeTok{tl.cex=}\NormalTok{.}\DecValTok{6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-64-1.pdf} Se
analiza adicionalmente la correlación de forma gráfica.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#par(mfrow = c(1,1))}
\CommentTok{\#cor.data \textless{}{-} cor(data)}
\CommentTok{\#corrplot(cor.data, method = \textquotesingle{}number\textquotesingle{})}
\end{Highlighting}
\end{Shaded}

Se pueden apreciar relaciones débiles entre residual sugar, free sulfur
dioxide, ph, fixed acidity y density.

Modelo de regresión lineal:

Incialmente realizamos un modelo lineal con las 4 variables mas
correlacionadas con la variable ``quality''

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(quality }\SpecialCharTok{\textasciitilde{}}\NormalTok{ alcohol }\SpecialCharTok{+}\NormalTok{volatile.acidity }\SpecialCharTok{+}\NormalTok{ sulphates }\SpecialCharTok{+}\NormalTok{ citric.acid )}
\FunctionTok{summary}\NormalTok{(modelo1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = quality ~ alcohol + volatile.acidity + sulphates + 
##     citric.acid)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.71408 -0.38590 -0.06402  0.46657  2.20393 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(>|t|)    
## (Intercept)       2.64592    0.20106  13.160  < 2e-16 ***
## alcohol           0.30908    0.01581  19.553  < 2e-16 ***
## volatile.acidity -1.26506    0.11266 -11.229  < 2e-16 ***
## sulphates         0.69552    0.10311   6.746 2.12e-11 ***
## citric.acid      -0.07913    0.10381  -0.762    0.446    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.6588 on 1594 degrees of freedom
## Multiple R-squared:  0.3361, Adjusted R-squared:  0.3345 
## F-statistic: 201.8 on 4 and 1594 DF,  p-value: < 2.2e-16
\end{verbatim}

Posteriormente realizamos un modelo lineal con las 5 variables más
correlacionadas con la variable ``quality'' (simplemente añadimos total
sulfur dioxide al modelo anterior)

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Intervalos de confianza}
\FunctionTok{confint}\NormalTok{(modelo1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                       2.5 %     97.5 %
## (Intercept)       2.2515575  3.0402782
## alcohol           0.2780728  0.3400835
## volatile.acidity -1.4860436 -1.0440733
## sulphates         0.4932780  0.8977542
## citric.acid      -0.2827462  0.1244961
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# En caso de querer los intervalos basados en el error estándar.}
\FunctionTok{confint.default}\NormalTok{(modelo1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                       2.5 %     97.5 %
## (Intercept)       2.2518569  3.0399788
## alcohol           0.2780963  0.3400600
## volatile.acidity -1.4858758 -1.0442411
## sulphates         0.4934316  0.8976006
## citric.acid      -0.2825916  0.1243415
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo2 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(quality }\SpecialCharTok{\textasciitilde{}}\NormalTok{ alcohol }\SpecialCharTok{+}\NormalTok{volatile.acidity }\SpecialCharTok{+}\NormalTok{ sulphates }\SpecialCharTok{+}\NormalTok{ citric.acid }\SpecialCharTok{+}\NormalTok{ total.sulfur.dioxide)}
\FunctionTok{summary}\NormalTok{(modelo2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = quality ~ alcohol + volatile.acidity + sulphates + 
##     citric.acid + total.sulfur.dioxide)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.72463 -0.38380 -0.06689  0.44606  2.14550 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(>|t|)    
## (Intercept)           2.8431068  0.2050732  13.864  < 2e-16 ***
## alcohol               0.2953419  0.0160375  18.416  < 2e-16 ***
## volatile.acidity     -1.2223102  0.1124774 -10.867  < 2e-16 ***
## sulphates             0.7207881  0.1027039   7.018 3.32e-12 ***
## citric.acid          -0.0427246  0.1035810  -0.412     0.68    
## total.sulfur.dioxide -0.0022182  0.0005126  -4.327 1.60e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.6552 on 1593 degrees of freedom
## Multiple R-squared:  0.3439, Adjusted R-squared:  0.3418 
## F-statistic:   167 on 5 and 1593 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Intervalos de confianza}
\FunctionTok{confint}\NormalTok{(modelo2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                             2.5 %       97.5 %
## (Intercept)           2.440865047  3.245348455
## alcohol               0.263885167  0.326798655
## volatile.acidity     -1.442929393 -1.001690996
## sulphates             0.519339183  0.922237030
## citric.acid          -0.245894093  0.160444848
## total.sulfur.dioxide -0.003223673 -0.001212781
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# En caso de querer los intervalos basados en el error estándar.}
\FunctionTok{confint.default}\NormalTok{(modelo2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                             2.5 %       97.5 %
## (Intercept)           2.441170667  3.245042835
## alcohol               0.263909067  0.326774754
## volatile.acidity     -1.442761768 -1.001858621
## sulphates             0.519492243  0.922083970
## citric.acid          -0.245739727  0.160290481
## total.sulfur.dioxide -0.003222909 -0.001213545
\end{verbatim}

Finalmente realizamos un modelo lineal con las 7 variables mas
correlacionadas con la variable ``quality'' (simplemente añadimos total
density al modelo anterior)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo3 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(quality }\SpecialCharTok{\textasciitilde{}}\NormalTok{ alcohol }\SpecialCharTok{+}\NormalTok{volatile.acidity }\SpecialCharTok{+}\NormalTok{ sulphates }\SpecialCharTok{+}\NormalTok{ citric.acid }\SpecialCharTok{+}\NormalTok{ chlorides }\SpecialCharTok{+}\NormalTok{total.sulfur.dioxide }\SpecialCharTok{+}\NormalTok{density)}
\FunctionTok{summary}\NormalTok{(modelo3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = quality ~ alcohol + volatile.acidity + sulphates + 
##     citric.acid + chlorides + total.sulfur.dioxide + density)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.67819 -0.38067 -0.06311  0.44428  2.05461 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(>|t|)    
## (Intercept)          -0.9529094 11.9896065  -0.079    0.937    
## alcohol               0.2802878  0.0202744  13.825  < 2e-16 ***
## volatile.acidity     -1.1144889  0.1197464  -9.307  < 2e-16 ***
## sulphates             0.9025477  0.1122700   8.039 1.75e-15 ***
## citric.acid           0.0444070  0.1236454   0.359    0.720    
## chlorides            -1.7474785  0.4056573  -4.308 1.75e-05 ***
## total.sulfur.dioxide -0.0023195  0.0005138  -4.514 6.82e-06 ***
## density               3.9230934 11.9441494   0.328    0.743    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.6517 on 1591 degrees of freedom
## Multiple R-squared:  0.3517, Adjusted R-squared:  0.3488 
## F-statistic: 123.3 on 7 and 1591 DF,  p-value: < 2.2e-16
\end{verbatim}

Al revisar R-squared, se observa cómo al ir incluyendo más variables se
mejora, aunque no mucho, la precisión del modelo.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Intervalos de confianza}
\FunctionTok{confint}\NormalTok{(modelo3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                              2.5 %       97.5 %
## (Intercept)          -24.469996853 22.564178123
## alcohol                0.240520525  0.320055120
## volatile.acidity      -1.349366182 -0.879611611
## sulphates              0.682334966  1.122760383
## citric.acid           -0.198118011  0.286932040
## chlorides             -2.543157645 -0.951799434
## total.sulfur.dioxide  -0.003327297 -0.001311684
## density              -19.504831974 27.351018799
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# En caso de querer los intervalos basados en el error estándar.}
\FunctionTok{confint.default}\NormalTok{(modelo3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                              2.5 %       97.5 %
## (Intercept)          -24.452106293 22.546287563
## alcohol                0.240550778  0.320024867
## volatile.acidity      -1.349187499 -0.879790293
## sulphates              0.682502492  1.122592856
## citric.acid           -0.197933511  0.286747540
## chlorides             -2.542552334 -0.952404745
## total.sulfur.dioxide  -0.003326531 -0.001312451
## density              -19.487009244 27.333196069
\end{verbatim}

Regresion logistica:

Creamos una variable dicotómica para aplicar la regresión logistica.
CalidadAlta será igual a 1 cuando los valores de la variable quality
sean superiores o iguales a 6

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\SpecialCharTok{$}\NormalTok{CalidadAlta }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{( data}\SpecialCharTok{$}\NormalTok{quality }\SpecialCharTok{\textgreater{}=}\DecValTok{6}\NormalTok{ , }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\CommentTok{\#revisamos los valores}
\FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{quality, data}\SpecialCharTok{$}\NormalTok{CalidadAlta)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##       0   1
##   3  10   0
##   4  53   0
##   5 681   0
##   6   0 638
##   7   0 199
##   8   0  18
\end{verbatim}

Revisamos los valores introducidos en la nueva variable y su relación
con el contenido en la variable ``quality''

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model.logist1}\OtherTok{=}\FunctionTok{glm}\NormalTok{(}\AttributeTok{formula=}\NormalTok{CalidadAlta }\SpecialCharTok{\textasciitilde{}}\NormalTok{ alcohol }\SpecialCharTok{+}\NormalTok{volatile.acidity }\SpecialCharTok{+}\NormalTok{sulphates}\SpecialCharTok{+}\NormalTok{citric.acid }\SpecialCharTok{+}\NormalTok{chlorides}\SpecialCharTok{+}\NormalTok{total.sulfur.dioxide,   }\AttributeTok{data =}\NormalTok{ data,}\AttributeTok{family=}\FunctionTok{binomial}\NormalTok{(}\AttributeTok{link=}\NormalTok{logit))}
\FunctionTok{summary}\NormalTok{(model.logist1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = CalidadAlta ~ alcohol + volatile.acidity + sulphates + 
##     citric.acid + chlorides + total.sulfur.dioxide, family = binomial(link = logit), 
##     data = data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.0992  -0.8477   0.3166   0.8562   2.3680  
## 
## Coefficients:
##                      Estimate Std. Error z value Pr(>|z|)    
## (Intercept)          -8.48525    0.86548  -9.804  < 2e-16 ***
## alcohol               0.90564    0.07112  12.734  < 2e-16 ***
## volatile.acidity     -3.50967    0.45134  -7.776 7.48e-15 ***
## sulphates             2.91628    0.44170   6.602 4.05e-11 ***
## citric.acid          -0.89010    0.39249  -2.268   0.0233 *  
## chlorides             0.50032    2.45127   0.204   0.8383    
## total.sulfur.dioxide -0.01226    0.00205  -5.979 2.25e-09 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2209.0  on 1598  degrees of freedom
## Residual deviance: 1668.9  on 1592  degrees of freedom
## AIC: 1682.9
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\hypertarget{representaciuxf3n-de-los-resultados-a-partir-de-tablas-y-gruxe1ficas.}{%
\subsection{5. Representación de los resultados a partir de tablas y
gráficas.}\label{representaciuxf3n-de-los-resultados-a-partir-de-tablas-y-gruxe1ficas.}}

Relativo al contraste de hipotesis, podemos observar:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(}\StringTok{"ggplot2"}\NormalTok{)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{AlcoholCat }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{alcohol }\SpecialCharTok{\textless{}} \FloatTok{10.42}\NormalTok{ , }\StringTok{"Bajo"}\NormalTok{, }\StringTok{"Alto"}\NormalTok{)}
  \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{AlcoholCat,}\AttributeTok{y=}\NormalTok{quality, }\AttributeTok{color =}\NormalTok{ AlcoholCat )) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-74-1.pdf}
Esta representaación nos ayuda a observar fácilmente que existe una
diferencia notoria entre el grado de alcohol alto o bajo en relación con
la calidad. Podemos observar que para las muestras consideradas nivel de
alcohol Alto, se obtiene un valor de quality superior a la quality de
las muestras consideras nivel bajo de alcohol.

Visualizamos los datos asociados a cada modelo, en especial el grafico
Normal Q-Q y el gráfico de residuos frente valores ajustados,

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{layout}\NormalTok{(}\FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{),}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(modelo1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-75-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{layout}\NormalTok{(}\FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{),}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(modelo2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-76-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{layout}\NormalTok{(}\FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{),}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(modelo3)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-77-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Con las siguientes representaciones, nos hacemos una idea de cómo se comportan las variables alcohol,volatile.acidity, sulphates, citric.acid, total.sulfur.dioxide y density, en relación con la calidad del vino}
\FunctionTok{scatter.smooth}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{quality, data}\SpecialCharTok{$}\NormalTok{alcohol)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-78-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{scatter.smooth}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{quality, data}\SpecialCharTok{$}\NormalTok{volatile.acidity)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-78-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{scatter.smooth}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{quality, data}\SpecialCharTok{$}\NormalTok{sulq)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-78-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{scatter.smooth}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{quality, data}\SpecialCharTok{$}\NormalTok{citric.acid)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-78-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{scatter.smooth}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{quality, data}\SpecialCharTok{$}\NormalTok{total.sulfur.dioxide)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-78-5.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{scatter.smooth}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{quality, data}\SpecialCharTok{$}\NormalTok{density)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## pseudoinverse used at 5
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## neighborhood radius 1
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## reciprocal condition number 0
\end{verbatim}

\begin{verbatim}
## Warning in simpleLoess(y, x, w, span, degree = degree, parametric = FALSE, :
## There are other near singularities as well. 1
\end{verbatim}

\includegraphics{Practica2_files/figure-latex/unnamed-chunk-78-6.pdf}

Realizamos una tabla de comparación entre los modelos lineales
implementados.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Tabla con los coeficientes de determinación de cada modelo}
\NormalTok{tabla.coeficientes }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}
\DecValTok{1}\NormalTok{, }\FunctionTok{summary}\NormalTok{(modelo1)}\SpecialCharTok{$}\NormalTok{r.squared,}
\DecValTok{2}\NormalTok{, }\FunctionTok{summary}\NormalTok{(modelo2)}\SpecialCharTok{$}\NormalTok{r.squared,}
\DecValTok{3}\NormalTok{, }\FunctionTok{summary}\NormalTok{(modelo3)}\SpecialCharTok{$}\NormalTok{r.squared), }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{, }\AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(tabla.coeficientes) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Modelo"}\NormalTok{, }\StringTok{"R\^{}2"}\NormalTok{)}
\NormalTok{tabla.coeficientes}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Modelo       R^2
## [1,]      1 0.3361393
## [2,]      2 0.3438525
## [3,]      3 0.3516932
\end{verbatim}

Se observa que el modelo lineal 3 es ligeramente mejor que sus
predecesores.

Respecto al modelo logistico podemos realizar la visualización de los
odds ratio de las variables regresoras mediante un intervalo de
confianza del 95\% e interpreta los intervalos obtenidos. ¿Qué regresor
tiene más impacto en la probabilidad de calidad alta del vino?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{exp}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}\FunctionTok{coef}\NormalTok{(model.logist1),}\FunctionTok{confint}\NormalTok{(model.logist1)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Waiting for profiling to be done...
\end{verbatim}

\begin{verbatim}
##                                          2.5 %       97.5 %
## (Intercept)          2.064915e-04 3.704236e-05 1.103863e-03
## alcohol              2.473523e+00 2.157031e+00 2.851013e+00
## volatile.acidity     2.990667e-02 1.217130e-02 7.148419e-02
## sulphates            1.847251e+01 7.840845e+00 4.438928e+01
## citric.acid          4.106158e-01 1.894415e-01 8.832982e-01
## chlorides            1.649255e+00 1.269212e-02 1.944006e+02
## total.sulfur.dioxide 9.878187e-01 9.838110e-01 9.917551e-01
\end{verbatim}

Podemos indicar que el mayor impacto en incrementar la calidad del vino
es alcohol.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#install.packages("caret")}
\CommentTok{\#install.packages("e1071")}
 
\CommentTok{\#Import required library}
\FunctionTok{library}\NormalTok{(caret)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

Estimación de la precisión del modelo logistico Vamos a proporcionar la
tabla de confusión correspondiente al modelo.

Se adopta como criterio que las predicciones obtenidas con el modelo
logístico por encima de 0,5 pertenecerían al grupo de calidad alta.
Anteriormente hemos definido: CalidadAlta será igual a 1 cuando los
valores de la variable quality sean superiores o iguales a 6

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{confusionMatrix}\NormalTok{(}\FunctionTok{table}\NormalTok{(}\FunctionTok{predict}\NormalTok{(model.logist1, }\AttributeTok{type=}\StringTok{"response"}\NormalTok{) }\SpecialCharTok{\textgreater{}=} \FloatTok{0.5}\NormalTok{,data}\SpecialCharTok{$}\NormalTok{CalidadAlta }\SpecialCharTok{==} \StringTok{"1"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##        
##         FALSE TRUE
##   FALSE   539  213
##   TRUE    205  642
##                                         
##                Accuracy : 0.7386        
##                  95% CI : (0.7163, 0.76)
##     No Information Rate : 0.5347        
##     P-Value [Acc > NIR] : <2e-16        
##                                         
##                   Kappa : 0.475         
##                                         
##  Mcnemar's Test P-Value : 0.7321        
##                                         
##             Sensitivity : 0.7245        
##             Specificity : 0.7509        
##          Pos Pred Value : 0.7168        
##          Neg Pred Value : 0.7580        
##              Prevalence : 0.4653        
##          Detection Rate : 0.3371        
##    Detection Prevalence : 0.4703        
##       Balanced Accuracy : 0.7377        
##                                         
##        'Positive' Class : FALSE         
## 
\end{verbatim}

Se obteniene de esta manera que el modelo logístico tiene una precisión
superior al 70\%.

\hypertarget{resoluciuxf3n-del-problema.-a-partir-de-los-resultados-obtenidos-cuuxe1les-son-las-conclusiones-los-resultados-permiten-responder-al-problema}{%
\subsection{6. Resolución del problema. A partir de los resultados
obtenidos, ¿cuáles son las conclusiones? ¿Los resultados permiten
responder al
problema?}\label{resoluciuxf3n-del-problema.-a-partir-de-los-resultados-obtenidos-cuuxe1les-son-las-conclusiones-los-resultados-permiten-responder-al-problema}}

En el preprocesamiento de los datos valores extremos (outliers), se han
utilizado los siguientes criterios adoptados según las variables del
conjunto de datos: -residual.sugar: Se decide que los valores por encima
de 10 van a ser considerados outliers. -chlorides: se decide considerar
outliers a los valores superiores a 0,3 -free.sulfur.dioxide: se decide
considerar outliers los valores por encima de 60. -total.sulfur.dioxide:
se considerar outliers los valores por encima de 170. -sulphates: se
decide considerar outliers los valores por encima de 1,5.

A todos esos casos se ha decidido imputar el valor de la mediana,
exluidos los casos considerados outliers.\\
En el resto de variables. no se han realizado modificaciones de los
datos.

De análisis de los datos, podemos indicar que:

Del contraste de hipotesis realizado, la calidad de los vinos es
diferente entre los considerados como nivel bajo de alcohol y nivel
alto, con un nivel de confianza del 95\%. Por lo observado, parece que
el nivel de calidad puede ser superior para los vinos con un nivel alto
de alcohol.

Del análisis de la correlaciones podemos indicar que las variables
alcohol, volatile.acidity, sulphates, citric.acid y chlorides son las
más correlacionadas con el nivel de calidad de los vinos del dataset.
Esto significa que son las variables del dataset que ejercen una mayor
influencia sobre el la calidad del vino.

Adicionalmente hemos realizados diferentes modelos de regresión,
lineales y logística, que serían útiles para realizar predicciones sobre
la calidad dadas unas características concretas, de las otras variables.

De lo anterior podemos indicar que del análisis de los datos podemos
aclarar cómo algunas de las variables del conjunto de datos están
relacionadas con el problema planteado, conocer la calidad del vino.

\hypertarget{cuxf3digo-hay-que-adjuntar-el-cuxf3digo-preferiblemente-en-r-con-el-que-se-ha-realizado-la-limpieza-anuxe1lisis-y-representaciuxf3n-de-los-datos.-si-lo-preferuxeds-tambiuxe9n-poduxe9is-trabajar-en-python.}{%
\subsection{7. Código: Hay que adjuntar el código, preferiblemente en R,
con el que se ha realizado la limpieza, análisis y representación de los
datos. Si lo preferís, también podéis trabajar en
Python.}\label{cuxf3digo-hay-que-adjuntar-el-cuxf3digo-preferiblemente-en-r-con-el-que-se-ha-realizado-la-limpieza-anuxe1lisis-y-representaciuxf3n-de-los-datos.-si-lo-preferuxeds-tambiuxe9n-poduxe9is-trabajar-en-python.}}

\#exportacion de datos tras el tratamiento:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{write.csv}\NormalTok{(data,}\StringTok{"C:}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{Users}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{Usuario}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{winquality\_modificado.csv"}\NormalTok{, }\AttributeTok{row.names =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}


\end{document}
